pipeline:
  build:
    image: rust:1.25
    commands:
    - cargo build --release
  package:
    image: rust:1.25
    commands:
    - tar -czvf saml2aws_auto.tar.gz target/release/saml2aws-auto
    when:
      event: tag
