# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=saml2aws-auto

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    # - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    # - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: qdd5MgrXtDNZsIJY7dfHBkUMFP+Q75yxL4yZSOPCXknY8rkdckShKwdpIBx8zuJfRFTtnpakMeRKwQbb6fwvdmUKHg8wLOo48Km0oX3VBHbDd8iLYDDJctlOBfhGWBWy6wQeob0phS0GU6ML/PCEupOqkW8M3m0qXuulPArhT23fRkuHRW2ifZzK/cMV4DZtskYFLQRAx1Gwt69CToSgrSnrxEdC9mmcE4e1xSNZSSQlqUR8R6I5Z6+1HmAY0wLrS5xnJfXWSiAz3zbryspGz9m/xCA5fQ8rKsGUj8Jt/w8/w8qg96Ds2xy+s2+CUTb2VRS7cbTJQILkrqyv3g2y5FNTlrd8KqQNBWLTY0WwKOD1LV6oYyFG0o5sSjf8Is4YCy01uTrWrrgcfI+dNSButK4NzHdKxn6U+nN/lyeMltSwKUfJdg7r+gh4GFgPxB0tRiOWQVAGa/4AF0kOyyZHArIykUkc2sl9nIBqpyHwbhD77bcVyRwEWvxIoYP2hd2tz769rzWcYLmZUmIQsw2VQFMQ0izz6NFGB3nwaEJld97NvzImGGi3Dr6bVu/WDS4V5YatlmlzWwc+ls5GEQNRLyMtXRfEykiemYDa/FwvyFg6RwCNFbfS7qnNcsFnU8U9Fw1j8ClMXgraXKInpl7L+HxmarDJHflKsLrvS/IHO0Y=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
