[package]
name = "saml2aws-auto"
version = "0.1.3"
authors = ["Jan Christopehrsen <jan.christophersen@digitalunit.berlin>"]

[dependencies]
clap = {version = "2.31", features = ["yaml"]}
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
crossterm = "0.2"
chrono = { version = "0.4", features = ["serde"] }
